### PR TITLE
Add error handler integration tests

### PR DESCRIPTION
**Pull request by sdeleuze**
Related to issue #47, WIP so do not merge yet.
Currently fails with RxNetty (ok with others).

### CODE REVIEW

**Comment by sdeleuze** [comment]
@smaldini: Could you have a look to the stacktrace to check it is not related to some issue in the `Publisher` -> `Observable` conversion by reactor core? I would like to be sure the error is correctly propagated to the RxJava `Observable`.

```
2015-12-14 11:57:31,000 ERROR [io.reactivex.netty.protocol.http.server.HttpServerImpl] <rxnetty-nio-eventloop-1-7> - Unexpected error while processing request.
java.lang.IllegalStateException
	at org.springframework.web.reactive.handler.SimpleUrlHandlerMappingIntegrationTests$ErrorHandler.handle(SimpleUrlHandlerMappingIntegrationTests.java:167)
	at org.springframework.web.reactive.handler.HttpHandlerAdapter.handle(HttpHandlerAdapter.java:57)
	at org.springframework.web.reactive.DispatcherHandler.lambda$handle$12(DispatcherHandler.java:107)
	at org.springframework.web.reactive.DispatcherHandler$$Lambda$4/20104050.apply(Unknown Source)
	at reactor.core.publisher.operator.FlatMapOperator$MergeBarrier.doNext(FlatMapOperator.java:135)
	at reactor.core.subscriber.SubscriberBarrier.onNext(SubscriberBarrier.java:85)
	at org.springframework.web.reactive.DispatcherHandler.lambda$first$14(DispatcherHandler.java:137)
	at org.springframework.web.reactive.DispatcherHandler$$Lambda$3/1239394719.accept(Unknown Source)
	at reactor.core.publisher.PublisherFactory$ConsumerSubscriberBarrier.doNext(PublisherFactory.java:665)
	at reactor.core.subscriber.SubscriberBarrier.onNext(SubscriberBarrier.java:85)
	at reactor.core.publisher.operator.FlatMapOperator$MergeBarrier.tryEmit(FlatMapOperator.java:267)
	at reactor.core.publisher.operator.FlatMapOperator$BufferSubscriber.onNext(FlatMapOperator.java:604)
	at reactor.core.subscriber.SubscriberWithContext.onNext(SubscriberWithContext.java:89)
	at org.springframework.web.reactive.handler.SimpleUrlHandlerMapping.lambda$getHandler$18(SimpleUrlHandlerMapping.java:50)
	at org.springframework.web.reactive.handler.SimpleUrlHandlerMapping$$Lambda$6/226868489.accept(Unknown Source)
	at reactor.core.publisher.PublisherFactory$ForEachBiConsumer.accept(PublisherFactory.java:584)
	at reactor.core.publisher.PublisherFactory$ForEachBiConsumer.accept(PublisherFactory.java:553)
	at reactor.core.publisher.PublisherFactory$SubscriberProxy.request(PublisherFactory.java:488)
	at reactor.core.publisher.operator.FlatMapOperator$BufferSubscriber.onSubscribe(FlatMapOperator.java:598)
	at reactor.core.publisher.PublisherFactory$ReactorPublisher.subscribe(PublisherFactory.java:302)
	at reactor.core.publisher.operator.FlatMapOperator$MergeBarrier.doNext(FlatMapOperator.java:148)
	at reactor.core.subscriber.SubscriberBarrier.onNext(SubscriberBarrier.java:85)
	at reactor.core.subscriber.SubscriberWithContext.onNext(SubscriberWithContext.java:89)
	at reactor.core.publisher.ForEachSequencer.accept(ForEachSequencer.java:41)
	at reactor.core.publisher.ForEachSequencer$IterableSequencer.accept(ForEachSequencer.java:55)
	at reactor.core.publisher.PublisherFactory$ForEachBiConsumer.accept(PublisherFactory.java:584)
	at reactor.core.publisher.PublisherFactory$ForEachBiConsumer.accept(PublisherFactory.java:553)
	at reactor.core.publisher.PublisherFactory$SubscriberProxy.request(PublisherFactory.java:488)
	at reactor.core.publisher.operator.FlatMapOperator$MergeBarrier.doOnSubscribe(FlatMapOperator.java:126)
	at reactor.core.subscriber.SubscriberBarrier.onSubscribe(SubscriberBarrier.java:67)
	at reactor.core.publisher.PublisherFactory$ReactorPublisher.subscribe(PublisherFactory.java:302)
	at reactor.core.publisher.PublisherFactory$PublisherOperator.subscribe(PublisherFactory.java:371)
	at reactor.core.publisher.PublisherFactory$PublisherOperator.subscribe(PublisherFactory.java:371)
	at reactor.core.publisher.PublisherFactory$PublisherOperator.subscribe(PublisherFactory.java:371)
	at reactor.core.publisher.PublisherFactory$PublisherOperator.subscribe(PublisherFactory.java:371)
	at reactor.core.publisher.convert.RxJava1Converter$1.call(RxJava1Converter.java:55)
	at reactor.core.publisher.convert.RxJava1Converter$1.call(RxJava1Converter.java:51)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:8098)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:172)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:136)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:79)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:97)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:73)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:49)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:32)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.unsafeSubscribe(Observable.java:8098)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:172)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:136)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:79)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.slowpath(OnSubscribeFromIterable.java:97)
	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:73)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:49)
	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:32)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable$2.call(Observable.java:162)
	at rx.Observable$2.call(Observable.java:154)
	at rx.Observable.subscribe(Observable.java:8191)
	at rx.Observable.subscribe(Observable.java:8158)
	at rx.Observable.subscribe(Observable.java:7872)
	at io.reactivex.netty.protocol.http.server.HttpServerImpl$HttpServerConnectionHandler$RequestHandlingOperator$1.onNext(HttpServerImpl.java:309)
	at io.reactivex.netty.protocol.http.server.HttpServerImpl$HttpServerConnectionHandler$RequestHandlingOperator$1.onNext(HttpServerImpl.java:267)
	at io.reactivex.netty.protocol.http.internal.AbstractHttpConnectionBridge$ConnectionInputSubscriber.nextHeader(AbstractHttpConnectionBridge.java:565)
	at io.reactivex.netty.protocol.http.internal.AbstractHttpConnectionBridge$ConnectionInputSubscriber.access$300(AbstractHttpConnectionBridge.java:454)
	at io.reactivex.netty.protocol.http.internal.AbstractHttpConnectionBridge.processNextItemInEventloop(AbstractHttpConnectionBridge.java:207)
	at io.reactivex.netty.protocol.http.internal.AbstractHttpConnectionBridge.access$1300(AbstractHttpConnectionBridge.java:51)
	at io.reactivex.netty.protocol.http.internal.AbstractHttpConnectionBridge$ConnectionInputSubscriber.onNext(AbstractHttpConnectionBridge.java:499)
	at io.reactivex.netty.protocol.tcp.AbstractConnectionToChannelBridge$ReadProducer.sendOnNext(AbstractConnectionToChannelBridge.java:346)
	at io.reactivex.netty.protocol.tcp.AbstractConnectionToChannelBridge.newMessage(AbstractConnectionToChannelBridge.java:183)
	at io.reactivex.netty.protocol.tcp.BackpressureManagingHandler.channelRead(BackpressureManagingHandler.java:73)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rstoyanchev** [comment]
Now that we have HttpExceptionHandler perhaps it makes sense to use one for the testErrorHandler test or otherwise we are letting the error escape and relying on the runtime behavior.

**Comment by sdeleuze** [comment]
@rstoyanchev Indeed! Since my goal is also to make exception handling usable for applications like [`spring-reactive-playground`](https://github.com/sdeleuze/spring-reactive-playground), `DispatcherHandler` could perhaps auto-detect `HttpExceptionHandler` and use `ErrorHandlingHttpHandler` to add the exception handling behavior? 

But since `DispatcherHandler` only deals with `Object` handlers, not `HttpHandler` handlers, I am not sure how to do that exactly. Any thoughts?

**Comment by rstoyanchev** [comment]
Indeed DispatcherHandler wouldn't be the one to detect neither HttpExceptionHandler nor HttpFilter instances. These [two tests](https://github.com/spring-projects/spring-reactive/blob/fea326ddb8b08aa346d5c765d240897f9d47b880/src/test/java/org/springframework/web/reactive/DispatcherHandlerErrorTests.java#L172-L195) show how to set it up. 

Eventually there will be some higher-level, auto-detection, mechanism or WebApplicationInitializer-like API for initializing DispatcherHandler with a Filter chain and exception handling but for now it be done manually.

**Pull request closed without merging**
