### PR TITLE
Byte buffer abstraction

### PR DESCRIPTION
**Pull request by poutsma**
For your reviewing convenience, I've split this large PR into four commits: the fist commit introduces the abstraction, the second and third refactor the codebase to use it, and the fourth removes some unnecessary classes.

### CODE REVIEW

**Comment by sdeleuze** [comment]
:+1: for most of the PR. My main remark is about `DataBuffer` tests. It seems `DataBufferTests` has been removed and the remaining `DefaultDataBufferTests` contains just a single test. Is it voluntary or not?

**Comment by poutsma** [comment]
Ug. That should have been the other way around: DefaultDataBufferTests should have been removed, as it contains no useful tests.
Let me try and fix that.

**Comment by poutsma** [comment]
Fixed. Thanks for the keen eye!

**Comment by bclozel** [comment]
Looks good!
We should merge this as soon as possible; or we can push additional commits on master and let you fall into rebase hell :smiling_imp:

**Comment by sdeleuze** [comment]
:+1:

**Pull request merged**
