### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by joaoevangelista**

### CODE REVIEW

**Comment by sdeleuze** [comment]
Hi, and thanks for your PR.

Could you merge your 2 commits in a single one?
I also prefer avoiding JAXBContextUtils, so even if there is a small duplication here, I think we can keep the code as it is now for that part.

Could you also please [sign our CLA](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#sign-the-contributor-license-agreement) and put a comment here when it is done?

**Comment by rstoyanchev** [comment]
Indeed a utils class with just one method isn't worth it for now while we are still experimenting.

**Comment by joaoevangelista** [comment]
Thank you guys, I have already signed the CLA in the past and I have squashed commits into one

**Comment by sdeleuze** [comment]
Merged, thanks!

**Pull request closed without merging**
