### PR TITLE
Proposal for Filter functionality

### PR DESCRIPTION
**Pull request by rstoyanchev**
A starting point for Filter-like functionality. 

The new `ReactiveHttpFilter` contract is similar to the existing `ReactiveHttpHandler` except it allows delegating to a filter chain, i.e. to the next thing in the chain.

There is also a `FilterChainHttpHandler` (an `ReactiveHttpHandler` itself) that forms the filter chain from a list of filters and a target handler.

### CODE REVIEW

**Comment by sdeleuze** [comment]
I think `Interceptor` is a better term than `Filter` because:
- It is the term we use in Spring Framework currently, but since `HandlerInterceptor` is servlet specific, we will have to provide a non Servlet based + Reactive alternative, like we have done for HTTP request and response
- Interceptor is more accurate and general, and it is relevant for both client and server (`LoggingInterceptor` make sense for both for example)
- We could consider that Servlet `Filter` and Spring MVC `HandlerInterceptor` are going to be unified in this new `Filter`/`Interceptor` class we are discussing, and I agree this class should be in `org.springframework.http` package.
 
 What about `org.springframework.http.server.ReactiveServerHttpInterceptor` and `org.springframework.client.http.ReactiveClientHttpInterceptor`?

**Comment by smaldini** [comment]
I like Interceptor although I think it should extend 3 separate interfaces and provide for default interface methods :
- Pre Processor
- Post Processor
- Post Write Processor

**Comment by sdeleuze** [comment]
+1 for default methods here !

But what would be the advantages of providing 3 separated interfaces?
I mean default methods make me think that a single interface with 2 or 3 methods is fine, since people implementing it will only have to implement a single method if they just need that.

**Comment by smaldini** [comment]
That's true @sdeleuze, but that mean we pay the overhead of wiring NooP operations where the pipeline could just find a given type to wire.

**Comment by sdeleuze** [comment]
From my POV, this is a (small) cost worth to pay for a more simpler programming model @smaldini ;-) That's what we do currently in Spring Framework `HandlerInterceptorAdapter`.

**Comment by smaldini** [comment]
Updated the comment. Although it's not something to not consider IMO, I usually spend time in infinite stacks due to the chaining nature of Reactive Streams (and in particular Rx-like impls). It quickly adds up if you have just a few interceptor, everytime which results in 3 more "operators" no matters what. If we think we will have in average 4-6 interceptor for a given url, it's possibly 12-18 more operators. Imagine this :
- stream.map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx).map(xx)

**Comment by sdeleuze** [comment]
Good point @smaldini, but maybe we could define a convention (return `null` or `false` in the interface default method) that allows us to detect if a custom implementation of such method is provided, in order to only add conditionally just the necessary steps in the pipeline.

**Comment by rstoyanchev** [comment]
I think there is some confusion. Let me provide more context.

I believe there is a need for both global and for more fine-grained interception. By global I mean doing something at the start and end of a request such as applying security, compressing, etags with key focus on being able to decorate the request & response and preventing further processing. By more fine-grained I mean something more deeply integrated with the lifecycle of request handling of the web framework.

Tackling global interception first seems like a good starting point. Clearly there are many cases where that will be needed on its own (i.e. without fine-grained interception). Initially I started out with such global interceptors that were initialized and invoked within the DispatcherHandler. Eventually I realized that for such global interception there is no need for it to happen inside the DispatcherHandler.

That's where HttpFilter comes in. It is a low level contract on par with HttpHandler and is in fact almost identical to it with the additional "chain" argument. So now instead of running DispatcherHandler you'd run the FilterChainHttpHandler which an HttpHandler that invokes a chain of HttpFilter's followed by a target HttpHandler (the DispatcherHandler).

What's nice about this is it's a mechanism that's independent of DispatcherHandler-specific web framework functionality and it can be used with other handlers. Also it's quite easy to replace the FilterChainHttpHandler if you can imagine a different way of chaining request handling.

As for the name, I think Filter is not a bad name at all. Filtering, proxying, and intercepting are all in the right category. I do like Filter also for it's similarity to a Servlet Filter, it's a correct analogy.

Regarding pre- and post-process functions chained with map, that was what I tried in the original prototype but that only supports sync semantics. The `Publisher<Void>` return value in the current proposal ensures the ability to do something asynchronous while also preserving synchronous invocation semantics (the actual request and response passed in) by default which is the 80% scenario. It's really the same contract as HttpHandler with HttpFilter being a variant that can delegate to the next thing in a chain. You can also do the same with a chain of HttpHandler's except here we are explicitly designating filters vs a handler at the end.

**Comment by sdeleuze** [comment]
Ok, thanks for the detailed explanation about global versus fine-grained interception.

One remaining concern I have is that this kind of global interception make also sense on client side, and I think it would be nice to use the same terms on client and server when we are talking about the same kind of things. But I am not sure `HttpFilter` make sense on client side. Any thoughts?

**Comment by rstoyanchev** [comment]
Yes let's see what we end up with on the client side and decide. If the concepts are the same we should align the names. However I do think there are significant differences. HttpHandler is strictly a server-side concept for example and so is HttpFilter which is almost identical. There is just no concept of handling or filtering/proxying a request on the client side.

**Comment by rstoyanchev** [comment]
This is now in master.

**Pull request closed without merging**
